# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20171221_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
