# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20171222_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
